import { Kecamatan, Menu } from "@/type";

const mainMenu: Menu[] = [
  { label: "BUMN dan Swasta", url: "/bumn-dan-swasta" },
  { label: "Kecamatan", url: "/kecamatan" },
  { label: "Nagari", url: "/nagari" },
  { label: "OPD", url: "/opd" },
  { label: "VERTIKAL", url: "/vertikal" },
];

const nagari = [
  { key: 1, label: "Aia Bangih" },
  { key: 2, label: "Desa Baru" },
  { key: 3, label: "Batahan" },
  { key: 4, label: "Desa Baru Barat" },
  { key: 5, label: "Batahan Utara" },
  { key: 6, label: "Batahan Tengah" },
  { key: 7, label: "Batahan Barat" },
  { key: 8, label: "Batahan Selatan" },
  { key: 9, label: "Parik" },
  { key: 10, label: "Koto Tangah" },
  { key: 11, label: "Koto Tuo" },
  { key: 12, label: "Koto Nan Duo" },
  { key: 13, label: "Pamatang Panjang" },
  { key: 14, label: "Ranah Koto Tinggi" },
  { key: 15, label: "Sungai Aua" },
  { key: 16, label: "Salingka Muaro" },
  { key: 17, label: "Ranah Malintang" },
  { key: 18, label: "Ranah Air Haji" },
  { key: 19, label: "Kasik Putih Sungai Tanang" },
  { key: 20, label: "Aua Serumpun" },
  { key: 21, label: "Sikilang Sungai Aur Selatan" },
  { key: 22, label: "Ujuang Gadiang" },
  { key: 23, label: "Brastagi Ujuang Gadiang" },
  { key: 24, label: "Tampus Damai Ujuang Gadiang" },
  { key: 25, label: "Taluak Ambun Ujuang Gadiang" },
  { key: 26, label: "Koto Gunung Ujuang Gadiang" },
  { key: 27, label: "Koto Sawah Ujuang Gadiang" },
  { key: 28, label: "Salido Saroha Ujuang Gadiang" },
  { key: 29, label: "Kuamang Alai Ujuang Gadiang" },
  { key: 30, label: "Situak Ujuang Gadiang" },
  { key: 31, label: "Muaro Kiawai" },
  { key: 32, label: "Rabi Jonggor" },
  { key: 33, label: "Muaro Kiawai Barat" },
  { key: 34, label: "Muaro Kiawai Hilir" },
  { key: 35, label: "Seberang Kenaikan" },
  { key: 36, label: "Bahoras" },
  { key: 37, label: "Ranah Sungai Magelang" },
  { key: 38, label: "Kajai" },
  { key: 39, label: "Talu" },
  { key: 40, label: "Sinuruik" },
  { key: 41, label: "Simpang Timbo Abu Kajai" },
  { key: 42, label: "Kajai Selatan" },
  { key: 43, label: "Sungai Janiah Talu" },
  { key: 44, label: "Tabek Sirah Talu" },
  { key: 45, label: "Lingkuang Aua" },
  { key: 46, label: "Aua Kuniang" },
  { key: 47, label: "Aia Gadang" },
  { key: 48, label: "Aia Gadang Timur" },
  { key: 49, label: "Aia Gadang Barat" },
  { key: 50, label: "Koto Baru" },
  { key: 51, label: "Kapa" },
  { key: 52, label: "Giri Maju" },
  { key: 53, label: "Ophir" },
  { key: 54, label: "Mahakarya" },
  { key: 55, label: "Sariak" },

  { key: 56, label: "Sungai Talang" },
  { key: 57, label: "Lambak Selatan" },
  { key: 58, label: "Pujo Rahayu" },
  { key: 59, label: "Sasak" },
  { key: 60, label: "Padang Harapan" },
  { key: 61, label: "Ranah Pasisie" },
  { key: 62, label: "Maligi" },
  { key: 63, label: "Katiagan" },
  { key: 64, label: "Kinali" },
  { key: 65, label: "Ampek Koto" },
  { key: 66, label: "Ampek Koto Barat" },
  { key: 67, label: "Bancah Kariang" },
  { key: 68, label: "Mudiak Labuah" },
  { key: 69, label: "Tandikek" },
  { key: 70, label: "Langgam Sepakat" },
  { key: 71, label: "Langgam Saiyo" },
  { key: 72, label: "Anam Koto Utara" },
  { key: 73, label: "Anam Koto Selatan" },
  { key: 74, label: "Sigunanti" },
  { key: 75, label: "Bandua Balai" },
  { key: 76, label: "Binuik" },
  { key: 77, label: "Padang Canduh" },
  { key: 78, label: "Limau Puruik" },
  { key: 79, label: "Koto Gadang Jaya" },

  { key: 80, label: "Lingkuang Aua Timur" },
  { key: 81, label: "Lingkuang Aua Baru" },
  { key: 82, label: "Lingkuang Aua Bandarjo" },
  { key: 83, label: "Lingkuang Aua Jambak" },
  { key: 84, label: "Lingkuang Aua Dalam" },
  { key: 85, label: "Lingkuang Aua Barat" },
  { key: 86, label: "Lingkuang Aua Hilia" },
  { key: 87, label: "Pinaga Aua Kuniang" },
  { key: 88, label: "Sukomananti Aua Kuniang" },
  { key: 89, label: "Lubuak Landua Aua Kuniang" },
  { key: 90, label: "Lembah Binuang Aua Kuniang" },
];

const bulan = [
  { key: 1, label: "Januari" },
  { key: 2, label: "Februari" },
  { key: 3, label: "Maret" },
  { key: 4, label: "April" },
  { key: 5, label: "Mei" },
  { key: 6, label: "Juni" },
  { key: 7, label: "Juli" },
  { key: 8, label: "Agustus" },
  { key: 9, label: "September" },
  { key: 10, label: "Oktober" },
  { key: 11, label: "November" },
  { key: 12, label: "Desember" },
];

const kecamatan: Kecamatan[] = [
  {
    key: 1,
    label: "Sungai Beremas",
  },
  {
    key: 2,

    label: "Ranah Batahan",
  },
  {
    key: 3,
    label: "Koto Balingka",
  },
  {
    key: 4,
    label: "Sungai Aur",
  },
  {
    key: 5,
    label: "Lembah Melintang",
  },
  {
    key: 6,
    label: "Gunung Tuleh",
  },
  {
    key: 7,
    label: "Talamau",
  },
  {
    key: 8,
    label: "Pasaman",
  },
  {
    key: 9,
    label: "Luhak Nan Duo",
  },
  {
    key: 10,
    label: "Sasak Ranah Pasisie",
  },
  {
    key: 11,
    label: "Kinali",
  },
];

const fasilitas = [
  { key: 1, label: "Ruang Rawat Inap" },
  { key: 2, label: "Tempat Tidur Tersedia" },
  { key: 3, label: "Ruang Perawatan Bersalin" },
  { key: 4, label: "Ruangan OK" },
  { key: 5, label: "Poliklinik Kebidanan" },
  { key: 6, label: "Poliklinik Bedah" },
  { key: 7, label: "IGD" },
  { key: 8, label: "Poliklinik Gigi" },
  { key: 9, label: "Poliklinik Umum" },
  { key: 10, label: "Poliklinik Anak" },
  { key: 11, label: "Apotik" },
  { key: 12, label: "Ruang Rontgen" },
  { key: 13, label: "Ruang Laboratorium" },
  { key: 14, label: "Ruangan Gizi" },
  { key: 15, label: "Poliklinik Mata" },
  { key: 16, label: "Bank Darah / BDRS" },
  { key: 17, label: "Poliklinik Fisioterapi" },
];

export { kecamatan, mainMenu, nagari, bulan, fasilitas };
